name: Run Specific Flink Planner Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-flink:
    runs-on: ubuntu-latest

    steps:
      - name: 🔻 Checkout source code
        uses: actions/checkout@v4

      - name: ☕ Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: 🔧 Run specific Flink test
        run: |
          mvn -pl flink-table/flink-table-planner test \
            -Dtest=org.apache.flink.table.planner.plan.rules.logical.PushPartitionIntoTableSourceScanRuleTest#testWithUdf
